services:
#    department_app.example:
#        class: Department\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    department_app.person_manager:
        class: Department\AppBundle\Service\Person
        arguments: ["@service_container"]
